<a href="https://colab.research.google.com/github/shubhs27/500107856_Predictive-Analytics-Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
array_1d_arange = np.arange(1, 6)
array_1d_linspace = np.linspace(1, 5, 5)

print("1D Array:")
print("Using np.array:", array_1d)
print("Using np.arange:", array_1d_arange)
print("Using np.linspace:", array_1d_linspace)

# 2D Array Creation
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d_zeros = np.zeros((2, 3))
array_2d_ones = np.ones((2, 3))
array_2d_eye = np.eye(3)

print("\n2D Array:")
print("Using np.array:", array_2d)
print("Using np.zeros:", array_2d_zeros)
print("Using np.ones:", array_2d_ones)
print("Using np.eye:", array_2d_eye)

# 3D Array Creation
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d_zeros = np.zeros((2, 2, 2))
array_3d_ones = np.ones((2, 2, 2))

print("\n3D Array:")
print("Using np.array:", array_3d)
print("Using np.zeros:", array_3d_zeros)
print("Using np.ones:", array_3d_ones)

# Basic Operations
# Indexing
element_2d = array_2d[1, 2]
element_3d = array_3d[1, 0, 1]
# Slicing
slice_1d = array_1d[1:4]
slice_2d = array_2d[:, 1]
slice_3d = array_3d[:, 0, :]

# Reshaping
reshaped_2d = array_2d.reshape((3, 2))
reshaped_3d = array_3d.reshape((4, 2))

# Concatenation
concatenated_1d = np.concatenate([array_1d, array_1d])
concatenated_2d = np.concatenate([array_2d, array_2d], axis=0)
concatenated_3d = np.concatenate([array_3d, array_3d], axis=0)

print("\nBasic Operations:")
print("Indexing 2D Array:", element_2d)
print("Indexing 3D Array:", element_3d)
print("Slicing 1D Array:", slice_1d)
print("Slicing 2D Array:", slice_2d)
print("Slicing 3D Array:", slice_3d)
print("Reshaped 2D Array:", reshaped_2d)
print("Reshaped 3D Array:", reshaped_3d)
print("Concatenated 1D Array:", concatenated_1d)
print("Concatenated 2D Array:", concatenated_2d)
print("Concatenated 3D Array:", concatenated_3d)

# Investigating Attributes
print("\nArray Attributes:")
print("Shape of 1D Array:", array_1d.shape)
print("Size of 1D Array:", array_1d.size)
print("Data Type of 1D Array:", array_1d.dtype)
print("Number of Dimensions of 1D Array:", array_1d.ndim)

print("Shape of 2D Array:", array_2d.shape)
print("Size of 2D Array:", array_2d.size)
print("Data Type of 2D Array:", array_2d.dtype)
print("Number of Dimensions of 2D Array:", array_2d.ndim)

print("Shape of 3D Array:", array_3d.shape)
print("Size of 3D Array:", array_3d.size)
print("Data Type of 3D Array:", array_3d.dtype)
print("Number of Dimensions of 3D Array:", array_3d.ndim)

# Methods
flattened = array_3d.flatten()  # Convert to 1D array
resized_2d = np.resize(array_2d, (3, 2))  # Resize to 3x2

print("\nArray Methods:")
print("Flattened 3D Array:", flattened)
print("Resized 2D Array:", resized_2d)


1D Array:
Using np.array: [1 2 3 4 5]
Using np.arange: [1 2 3 4 5]
Using np.linspace: [1. 2. 3. 4. 5.]

2D Array:
Using np.array: [[1 2 3]
 [4 5 6]]
Using np.zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Using np.ones: [[1. 1. 1.]
 [1. 1. 1.]]
Using np.eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3D Array:
Using np.array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Using np.zeros: [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Using np.ones: [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]

Basic Operations:
Indexing 2D Array: 6
Indexing 3D Array: 6
Slicing 1D Array: [2 3 4]
Slicing 2D Array: [2 5]
Slicing 3D Array: [[1 2]
 [5 6]]
Reshaped 2D Array: [[1 2]
 [3 4]
 [5 6]]
Reshaped 3D Array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated 1D Array: [1 2 3 4 5 1 2 3 4 5]
Concatenated 2D Array: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Concatenated 3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Array Attributes:
Shape of 1D Array: (5,)
Size of 1D Array: 5
Data Type of 1D Array: int64
Number of Di

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IRIS.csv')

print("Initial Data:")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

df.fillna(method='ffill', inplace=True)

df['species'] = df['species'].astype('category').cat.codes

feature_columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df[feature_columns] = df[feature_columns].apply(lambda x: (x - x.min()) / (x.max() - x.min()) if x.max() != x.min() else x)

mean_values = df[feature_columns].mean()
median_values = df[feature_columns].median()
std_dev_values = df[feature_columns].std()
variance_values = df[feature_columns].var()

print("\nMean Values:\n", mean_values)
print("\nMedian Values:\n", median_values)
print("\nStandard Deviation:\n", std_dev_values)
print("\nVariance:\n", variance_values)


Initial Data:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Missing Values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

Mean Values:
 sepal_length    0.428704
sepal_width     0.439167
petal_length    0.467571
petal_width     0.457778
dtype: float64

Median Values:
 sepal_length    0.416667
sepal_width     0.416667
petal_length    0.567797
petal_width     0.500000
dtype: float64

Standard Deviation:
 sepal_length    0.230018
sepal_width     0.180664
petal_length    0.299054
petal_width     0.317984
dtype: float64

Variance:
 sepal_length    0.052908
sepal_width     

<ipython-input-8-24718f2e2d83>:12: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)
